### ISSUE TITLE
TypeError: decode() argument 'errors' must be str, not None

### ISSUE THREAD

**Issue by bryant-finney** [saltstack/pytest-shell-utilities#31]
# Summary

While sampling this library, I experienced the following error:

```py
Traceback (most recent call last):
  File "/Users/bfinney/Library/Caches/pypoetry/virtualenvs/portals-f-u3IrZU-py3.9/lib/python3.9/site-packages/pytestshellutils/shell.py", line 259, in _terminate
    stdout = self._terminal._translate_newlines(  # type: ignore[attr-defined]
  File "/Users/bfinney/.pyenv/versions/3.9.11/lib/python3.9/subprocess.py", line 1011, in _translate_newlines
    data = data.decode(encoding, errors)
TypeError: decode() argument 'errors' must be str, not None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/bfinney/.pyenv/versions/3.9.11/lib/python3.9/doctest.py", line 1334, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest integration.tests.conftest.GitFixture[0]>", line 1, in <module>
  File "/Users/bfinney/projects/hometap/common/eng_portals/portals/integration/tests/conftest.py", line 54, in __init__
    self("init", *args, **kwargs)
  File "/Users/bfinney/projects/hometap/common/eng_portals/portals/integration/tests/conftest.py", line 57, in __call__
    return self.shell.run(*self._cmd, *args, **kwargs)
  File "/Users/bfinney/Library/Caches/pypoetry/virtualenvs/portals-f-u3IrZU-py3.9/lib/python3.9/site-packages/pytestshellutils/shell.py", line 498, in run
    result = self.terminate()
  File "/Users/bfinney/Library/Caches/pypoetry/virtualenvs/portals-f-u3IrZU-py3.9/lib/python3.9/site-packages/pytestshellutils/shell.py", line 446, in terminate
    return self.impl.terminate()
  File "/Users/bfinney/Library/Caches/pypoetry/virtualenvs/portals-f-u3IrZU-py3.9/lib/python3.9/site-packages/pytestshellutils/shell.py", line 202, in terminate
    return self._terminate()
  File "/Users/bfinney/Library/Caches/pypoetry/virtualenvs/portals-f-u3IrZU-py3.9/lib/python3.9/site-packages/pytestshellutils/shell.py", line 266, in _terminate
    stdout = self._terminal._translate_newlines(  # type: ignore[attr-defined]
TypeError: _translate_newlines() missing 1 required positional argument: 'errors'
```

## Additional Info

```sh
❯ pip show pytest-shell-utilities
Name: pytest-shell-utilities
Version: 1.6.0
Summary: Pytest plugin to simplify running shell commands against the system
Home-page: https://github.com/saltstack/pytest-shell-utilities
Author: Pedro Algarvio
Author-email: pedro@algarvio.me
License: Apache Software License 2.0
Location: /Users/bfinney/Library/Caches/pypoetry/virtualenvs/portals-f-u3IrZU-py3.9/lib/python3.9/site-packages
Requires: attrs, psutil, pytest, pytest-helpers-namespace, pytest-skip-markers, typing-extensions
Required-by: 


❯ python -c 'import platform; print(platform.platform())'
macOS-12.4-arm64-arm-64bit


❯ poetry env info

Virtualenv
Python:         3.9.11
Implementation: CPython
Path:           /Users/bfinney/Library/Caches/pypoetry/virtualenvs/portals-f-u3IrZU-py3.9
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /Users/bfinney/.pyenv/versions/3.9.11
```

**Comment by s0undt3ch** [comment]
Can you please run the following and report back?
```
❯ python
Python 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.errors
'strict'
>>>
```

**Comment by s0undt3ch** [comment]
Haven't heard back. Closing.
